"""Procedural art for DETACHED HEAD.

Every texture, sprite and banner in the game is generated by this module —
no external assets exist in the repository. Style: GitHub-dark terminal,
chunky pixels, 64x64 wall textures.
"""

from __future__ import annotations

import math
import random

import numpy as np
from PIL import Image, ImageDraw, ImageFont

TEX = 64  # wall texture resolution

BG = (13, 17, 23)  # github dark #0d1117
GREEN = (63, 185, 80)
RED = (248, 81, 73)
AMBER = (210, 153, 34)
PURPLE = (163, 113, 247)
CYAN = (39, 173, 190)
GRAY = (139, 148, 158)
WHITE = (230, 237, 243)
DARK = (22, 27, 34)


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    for name in ("consolab.ttf" if bold else "consola.ttf", "consolas.ttf", "cour.ttf", "lucon.ttf"):
        try:
            return ImageFont.truetype(f"C:/Windows/Fonts/{name}", size)
        except OSError:
            continue
    return ImageFont.load_default(size)


def _img(w: int, h: int, bg=(0, 0, 0, 0)) -> Image.Image:
    return Image.new("RGBA", (w, h), bg)


def _np(img: Image.Image) -> np.ndarray:
    return np.asarray(img.convert("RGB"), dtype=np.uint8)


# ---------------------------------------------------------------- wall textures

def tex_code() -> Image.Image:
    """A wall of source code: gutter, line numbers, coloured statement bars."""
    rng = random.Random(7)
    img = _img(TEX, TEX, BG + (255,))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 7, TEX - 1], fill=(10, 13, 18, 255))
    palette = [GREEN, (56, 139, 253), AMBER, PURPLE, (247, 120, 186), GRAY]
    y = 4
    ln = 1
    while y < TEX - 4:
        d.rectangle([2, y + 1, 5, y + 2], fill=(48, 54, 61, 255))  # line number stub
        x = 10
        for _ in range(rng.randint(1, 3)):
            seg = rng.randint(6, 20)
            color = rng.choice(palette)
            d.rectangle([x, y, min(x + seg, TEX - 3), y + 2], fill=color + (255,))
            x += seg + rng.randint(2, 5)
            if x > TEX - 8:
                break
        y += 6
        ln += 1
    return img


def tex_log() -> Image.Image:
    img = _img(TEX, TEX, (10, 12, 16, 255))
    d = ImageDraw.Draw(img)
    f = _font(8)
    lines = [
        ("INFO  deploy ok", GRAY),
        ("WARN  flaky test", AMBER),
        ("DEBUG heartbeat", (80, 90, 100)),
        ("ERROR nil deref", RED),
        ("INFO  retry 3/5", GRAY),
        ("WARN  tech debt", AMBER),
    ]
    y = 3
    for text, color in lines:
        d.text((3, y), text, font=f, fill=color + (255,))
        y += 10
    return img


def tex_warn() -> Image.Image:
    img = _img(TEX, TEX, BG + (255,))
    d = ImageDraw.Draw(img)
    for band in (0, TEX - 10):
        for x in range(-TEX, TEX, 12):
            d.polygon([(x, band + 10), (x + 6, band), (x + 18, band), (x + 12, band + 10)], fill=AMBER + (255,))
            d.polygon([(x + 12, band + 10), (x + 18, band), (x + 30, band), (x + 24, band + 10)], fill=(30, 22, 6, 255))
    f = _font(9, bold=True)
    d.text((6, 22), "MERGE", font=f, fill=RED + (255,))
    d.text((6, 34), "CONFLICT", font=f, fill=RED + (255,))
    return img


def tex_conflict() -> Image.Image:
    img = _img(TEX, TEX, BG + (255,))
    d = ImageDraw.Draw(img)
    f = _font(14, bold=True)
    d.text((4, 2), "<<<<<<", font=f, fill=(150, 45, 42, 255))
    d.rectangle([4, 24, 59, 38], fill=(120, 88, 26, 255))
    d.text((4, 44), ">>>>>>", font=f, fill=(150, 45, 42, 255))
    d.rectangle([0, 0, TEX - 1, TEX - 1], outline=(90, 34, 32, 255), width=1)
    return img


def tex_gate_wall() -> Image.Image:
    img = _img(TEX, TEX, (16, 14, 8, 255))
    d = ImageDraw.Draw(img)
    f = _font(8, bold=True)
    d.rectangle([0, 0, TEX - 1, TEX - 1], outline=AMBER + (255,))
    d.rectangle([22, 18, 41, 37], fill=(60, 44, 12, 255), outline=AMBER + (255,), width=2)  # padlock body
    d.arc([26, 6, 37, 20], 180, 360, fill=AMBER + (255,), width=3)  # shackle
    d.ellipse([29, 25, 34, 30], fill=AMBER + (255,))
    d.text((8, 44), "PROTECTED", font=f, fill=AMBER + (255,))
    return img


def tex_gate_open() -> Image.Image:
    """The merge gate, seen open once the LGTM key is held."""
    img = _img(TEX, TEX, (5, 8, 5, 255))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 9, TEX - 1], fill=GREEN + (255,))
    d.rectangle([TEX - 10, 0, TEX - 1, TEX - 1], fill=GREEN + (255,))
    d.rectangle([0, 0, TEX - 1, 6], fill=GREEN + (255,))
    f = _font(9, bold=True)
    d.text((12, 10), "LGTM", font=f, fill=GREEN + (255,))
    d.text((16, 24), "\u2713", font=f, fill=GREEN + (255,))
    return img


def make_textures() -> dict[str, np.ndarray]:
    out = {
        "code": tex_code(),
        "log": tex_log(),
        "warn": tex_warn(),
        "conflict": tex_conflict(),
        "gate_wall": tex_gate_wall(),
        "gate_open": tex_gate_open(),
    }
    return {k: _np(v) for k, v in out.items()}


# ---------------------------------------------------------------- sprites (RGBA)

def _bug(color) -> Image.Image:
    img = _img(32, 32)
    d = ImageDraw.Draw(img)
    dark = tuple(int(c * 0.55) for c in color)
    for i, xy in enumerate(((2, 8), (2, 14), (2, 20), (26, 8), (26, 14), (26, 20))):  # legs
        d.line([xy, (xy[0] + (6 if xy[0] < 16 else -6), xy[1] + (3 if i % 2 else -3))], fill=dark, width=2)
    d.ellipse([9, 9, 23, 23], fill=color)
    d.ellipse([12, 12, 20, 20], fill=dark)
    d.ellipse([11, 5, 14, 8], fill=color)  # head
    d.line([12, 5, 9, 1], fill=color, width=1)  # antennae
    d.line([13, 5, 16, 1], fill=color, width=1)
    d.point((12, 6), fill=WHITE)
    d.point((13, 6), fill=WHITE)
    return img


def _key_badge() -> Image.Image:
    img = _img(48, 48)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([2, 8, 45, 40], 6, fill=(35, 134, 54), outline=GREEN, width=2)
    f = _font(11, bold=True)
    d.text((8, 14), "LGTM", font=f, fill=WHITE)
    d.text((8, 26), "key", font=_font(10), fill=(180, 240, 190))
    return img


def _monolith(hp: int) -> Image.Image:
    """The LEGACY MONOLITH. hp 4 = pristine, hp 1 = shattered."""
    rng = random.Random(100 + hp)
    img = _img(96, 128)
    d = ImageDraw.Draw(img)
    slab = (31, 36, 41)
    d.rounded_rectangle([14, 2, 81, 126], 5, fill=slab, outline=(56, 63, 71), width=2)
    # moss of comments
    for _ in range(26):
        x, y = rng.randint(16, 78), rng.randint(4, 124)
        d.point((x, y), fill=(48, 55, 62))
        d.point((x + 1, y), fill=(40, 46, 52))
    # red eyes: dark slits, no overhanging glyph art
    eye = RED if hp > 1 else (120, 40, 36)
    d.rounded_rectangle([30, 18, 40, 26], 3, fill=eye)
    d.rounded_rectangle([56, 18, 66, 26], 3, fill=eye)
    d.rectangle([34, 21, 36, 23], fill=BG)
    d.rectangle([60, 21, 62, 23], fill=BG)
    # the glowing core: 10k lines of legacy
    core = max(hp - 1, 0)
    glow = [(40, 20, 16), (120, 40, 30), (200, 60, 45), (248, 90, 60)][core]
    d.rectangle([30, 44, 65, 102], fill=glow)
    d.rectangle([30, 44, 65, 102], outline=(20, 10, 8), width=1)
    f = _font(8, bold=True)
    d.text((35, 58), "10k", font=f, fill=BG)
    d.text((35, 70), "lines", font=f, fill=BG)
    # cracks grow as hp drops
    for i in range(4 - hp):
        x, y = rng.randint(20, 70), rng.randint(8, 110)
        for _ in range(9):
            d.line([(x, y), (x + rng.randint(-6, 6), y + rng.randint(2, 8))], fill=(200, 210, 220), width=1)
            x += rng.randint(-6, 6)
            y += rng.randint(2, 8)
    if hp == 1:  # about to fall apart
        d.line([14, 40, 81, 70], fill=(200, 210, 220), width=2)
        d.line([81, 30, 14, 90], fill=(160, 170, 180), width=1)
    return img


def make_sprites() -> dict[str, Image.Image]:
    return {
        "bug_red": _bug(RED),
        "bug_amber": _bug(AMBER),
        "bug_purple": _bug(PURPLE),
        "bug_green": _bug(GREEN),
        "bug_cyan": _bug(CYAN),
        "key": _key_badge(),
        "boss": _monolith(4),
        "boss3": _monolith(3),
        "boss2": _monolith(2),
        "boss1": _monolith(1),
    }


# ---------------------------------------------------------------- banners

def _scanlines(img: Image.Image) -> Image.Image:
    px = img.load()
    for y in range(3, img.height, 3):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            px[x, y] = (int(r * 0.72), int(g * 0.72), int(b * 0.72), a)
    return img


def make_title(w: int = 960, h: int = 600) -> Image.Image:
    img = _img(w, h, BG + (255,))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, w - 1, h - 1], outline=(48, 54, 61), width=2)
    f_big = _font(92, bold=True)
    f_sub = _font(26)
    f_menu = _font(30, bold=True)
    d.text((w // 2, 150), "DETACHED", font=f_big, fill=GREEN, anchor="mm")
    d.text((w // 2, 260), "HEAD", font=f_big, fill=GREEN, anchor="mm")
    d.text((w // 2, 360), "$ git checkout --detach", font=f_sub, fill=GRAY, anchor="mm")
    d.text((w // 2, 420), "a first-person shooter compiled into markdown", font=f_sub, fill=GRAY, anchor="mm")
    d.text((w // 2, 500), "press START", font=f_menu, fill=WHITE, anchor="mm")
    return _scanlines(img)


def make_win(w: int = 960, h: int = 600) -> Image.Image:
    img = _img(w, h, (6, 20, 10, 255))
    d = ImageDraw.Draw(img)
    f_big = _font(90, bold=True)
    f_sub = _font(26)
    d.text((w // 2, 170), "DEPLOYED", font=f_big, fill=GREEN, anchor="mm")
    d.text((w // 2, 280), "LEGACY MONOLITH DELETED", font=f_sub, fill=WHITE, anchor="mm")
    for i, line in enumerate(("build    \u2713 passed", "tests   \u2713 1337 passed", "deploy  \u2713 shipped to prod")):
        d.text((w // 2, 370 + i * 36), line, font=_font(24), fill=GRAY, anchor="mm")
    d.text((w // 2, 520), "merged. you may go home now.", font=f_sub, fill=GREEN, anchor="mm")
    return _scanlines(img)


def make_minimap_banner(lvl, w: int = 960, h: int = 600) -> Image.Image:
    """Standalone map overview for the README."""
    img = _img(w, h, BG + (255,))
    d = ImageDraw.Draw(img)
    cell = 20
    ox = (w - lvl.width * cell) // 2
    oy = (h - lvl.height * cell) // 2
    palette = {"arena": (70, 20, 20), "keyroom": (60, 50, 12), "gate": (70, 60, 20)}
    for y in range(lvl.height):
        for x in range(lvl.width):
            c = lvl.char(x, y)
            if lvl.is_floor(x, y):
                z = lvl.zone(x, y)
                color = palette.get(z, (27, 33, 41))
                if c == "G":
                    color = AMBER
                d.rectangle([ox + x * cell, oy + y * cell, ox + x * cell + cell - 2, oy + y * cell + cell - 2], fill=color)
            else:
                d.rectangle([ox + x * cell, oy + y * cell, ox + x * cell + cell - 2, oy + y * cell + cell - 2], fill=(13, 17, 23), outline=(48, 54, 61))
    d.ellipse([ox + lvl.spawn[0] * cell + 4, oy + lvl.spawn[1] * cell + 4, ox + lvl.spawn[0] * cell + cell - 6, oy + lvl.spawn[1] * cell + cell - 6], fill=GREEN)
    d.text((w // 2, oy - 40), "repo-01 \u00b7 the repository", font=_font(30, bold=True), fill=GREEN, anchor="mm")
    d.text((w // 2, h - 40), "find the LGTM key \u00b7 open the merge gate \u00b7 delete the LEGACY MONOLITH", font=_font(20), fill=GRAY, anchor="mm")
    return _scanlines(img)
