"""Procedural art for DETACHED HEAD.

Every texture, sprite and banner in the game is generated by this module —
no external assets exist in the repository. Style: GitHub-dark terminal,
chunky pixels, 64x64 wall textures.
"""

from __future__ import annotations

import math
import random

import numpy as np
from PIL import Image, ImageDraw, ImageFont

TEX = 64  # wall texture resolution

BG = (13, 17, 23)  # github dark #0d1117
GREEN = (63, 185, 80)
RED = (248, 81, 73)
AMBER = (210, 153, 34)
PURPLE = (163, 113, 247)
CYAN = (39, 173, 190)
GRAY = (139, 148, 158)
WHITE = (230, 237, 243)
DARK = (22, 27, 34)


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    for name in ("consolab.ttf" if bold else "consola.ttf", "consolas.ttf", "cour.ttf", "lucon.ttf"):
        try:
            return ImageFont.truetype(f"C:/Windows/Fonts/{name}", size)
        except OSError:
            continue
    return ImageFont.load_default(size)


def _img(w: int, h: int, bg=(0, 0, 0, 0)) -> Image.Image:
    return Image.new("RGBA", (w, h), bg)


def _np(img: Image.Image) -> np.ndarray:
    return np.asarray(img.convert("RGB"), dtype=np.uint8)


# ---------------------------------------------------------------- wall textures

def tex_code() -> Image.Image:
    """A wall of source code: gutter, line numbers, coloured statement bars."""
    rng = random.Random(7)
    img = _img(TEX, TEX, BG + (255,))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 7, TEX - 1], fill=(10, 13, 18, 255))
    palette = [GREEN, (56, 139, 253), AMBER, PURPLE, (247, 120, 186), GRAY]
    y = 4
    ln = 1
    while y < TEX - 4:
        d.rectangle([2, y + 1, 5, y + 2], fill=(48, 54, 61, 255))  # line number stub
        x = 10
        for _ in range(rng.randint(1, 3)):
            seg = rng.randint(6, 20)
            color = rng.choice(palette)
            d.rectangle([x, y, min(x + seg, TEX - 3), y + 2], fill=color + (255,))
            x += seg + rng.randint(2, 5)
            if x > TEX - 8:
                break
        y += 6
        ln += 1
    return img


def tex_log() -> Image.Image:
    img = _img(TEX, TEX, (10, 12, 16, 255))
    d = ImageDraw.Draw(img)
    f = _font(8)
    lines = [
        ("INFO  deploy ok", GRAY),
        ("WARN  flaky test", AMBER),
        ("DEBUG heartbeat", (80, 90, 100)),
        ("ERROR nil deref", RED),
        ("INFO  retry 3/5", GRAY),
        ("WARN  tech debt", AMBER),
    ]
    y = 3
    for text, color in lines:
        d.text((3, y), text, font=f, fill=color + (255,))
        y += 10
    return img


def tex_warn() -> Image.Image:
    img = _img(TEX, TEX, BG + (255,))
    d = ImageDraw.Draw(img)
    for band in (0, TEX - 10):
        for x in range(-TEX, TEX, 12):
            d.polygon([(x, band + 10), (x + 6, band), (x + 18, band), (x + 12, band + 10)], fill=AMBER + (255,))
            d.polygon([(x + 12, band + 10), (x + 18, band), (x + 30, band), (x + 24, band + 10)], fill=(30, 22, 6, 255))
    f = _font(9, bold=True)
    d.text((6, 22), "MERGE", font=f, fill=RED + (255,))
    d.text((6, 34), "CONFLICT", font=f, fill=RED + (255,))
    return img


def tex_conflict() -> Image.Image:
    img = _img(TEX, TEX, BG + (255,))
    d = ImageDraw.Draw(img)
    f = _font(14, bold=True)
    d.text((4, 2), "<<<<<<", font=f, fill=(150, 45, 42, 255))
    d.rectangle([4, 24, 59, 38], fill=(120, 88, 26, 255))
    d.text((4, 44), ">>>>>>", font=f, fill=(150, 45, 42, 255))
    d.rectangle([0, 0, TEX - 1, TEX - 1], outline=(90, 34, 32, 255), width=1)
    return img


def tex_gate_wall() -> Image.Image:
    """A barred portcullis with a padlock: reads as 'locked door' in any language."""
    img = _img(TEX, TEX, (20, 18, 14, 255))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, TEX - 1, TEX - 1], outline=(60, 44, 24, 255), width=3)  # stone frame
    for x in range(10, TEX - 8, 8):  # iron bars
        d.rectangle([x, 6, x + 3, TEX - 7], fill=(70, 62, 52, 255))
        d.rectangle([x, 6, x + 3, TEX - 7], outline=(30, 26, 22, 255))
    for y in (18, 44):  # cross bars
        d.rectangle([6, y, TEX - 7, y + 3], fill=(60, 54, 46, 255))
    d.rounded_rectangle([22, 22, 41, 41], 4, fill=(60, 44, 12, 255), outline=(247, 197, 66, 255), width=2)  # padlock
    d.arc([26, 10, 37, 24], 180, 360, fill=(247, 197, 66, 255), width=3)
    d.ellipse([29, 29, 34, 34], fill=(247, 197, 66, 255))
    return img


def tex_gate_open() -> Image.Image:
    """The same portcullis, raised: bars gone, warm light behind, way is open."""
    img = _img(TEX, TEX, (8, 10, 6, 255))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, TEX - 1, TEX - 1], outline=(60, 44, 24, 255), width=3)
    for x in range(10, TEX - 8, 8):  # only raised bar stubs at the top remain
        d.rectangle([x, 6, x + 3, 14], fill=(70, 62, 52, 255))
    d.rectangle([6, 6, TEX - 7, 9], fill=(60, 54, 46, 255))
    d.rectangle([10, 16, TEX - 11, TEX - 5], fill=(24, 30, 18, 255))  # the passage
    d.rectangle([10, 16, TEX - 11, TEX - 5], outline=GREEN + (255,))
    d.text((20, 30), "open", font=_font(11, bold=True), fill=GREEN + (255,))
    return img


def make_textures() -> dict[str, np.ndarray]:
    out = {
        "code": tex_code(),
        "log": tex_log(),
        "warn": tex_warn(),
        "conflict": tex_conflict(),
        "gate_wall": tex_gate_wall(),
        "gate_open": tex_gate_open(),
    }
    return {k: _np(v) for k, v in out.items()}


# ---------------------------------------------------------------- sprites (RGBA)

def _imp(color) -> Image.Image:
    """A frozen imp: horned blob with big white eyes. Must read as a creature
    at any distance, so: fat black outline, huge eyes, horns."""
    img = _img(48, 48)
    d = ImageDraw.Draw(img)
    dark = tuple(int(c * 0.45) for c in color)
    d.polygon([(11, 15), (6, 2), (18, 10)], fill=dark)  # horns
    d.polygon([(37, 15), (42, 2), (30, 10)], fill=dark)
    d.ellipse([6, 10, 42, 46], fill=(0, 0, 0))  # outline pass
    d.ellipse([8, 12, 40, 44], fill=color)
    d.ellipse([8, 12, 40, 44], outline=dark)
    d.ellipse([13, 19, 23, 30], fill=WHITE, outline=(0, 0, 0))  # eyes
    d.ellipse([25, 19, 35, 30], fill=WHITE, outline=(0, 0, 0))
    d.ellipse([16, 23, 20, 27], fill=(0, 0, 0))
    d.ellipse([28, 23, 32, 27], fill=(0, 0, 0))
    d.line([(15, 37), (19, 35), (23, 37), (27, 35), (31, 37)], fill=(0, 0, 0), width=2)  # jagged grin
    for ax, ay in ((4, 28), (44, 28)):  # stubby arms
        d.ellipse([ax - 3, ay - 3, ax + 3, ay + 3], fill=color, outline=dark)
    return img


def _key_badge() -> Image.Image:
    """The golden key. A key must look like a key: bow, shaft, teeth."""
    img = _img(48, 56)
    d = ImageDraw.Draw(img)
    gold = (247, 197, 66)
    gold_dark = (170, 120, 20)
    d.ellipse([3, 2, 35, 34], outline=gold_dark, width=9)  # halo/glow ring
    d.ellipse([6, 5, 30, 29], outline=gold, width=6)  # the bow
    d.rectangle([16, 28, 24, 54], fill=gold)  # shaft
    d.rectangle([16, 28, 24, 54], outline=gold_dark)
    d.rectangle([24, 44, 36, 50], fill=gold, outline=gold_dark)  # teeth
    d.rectangle([24, 33, 32, 38], fill=gold, outline=gold_dark)
    return img


def _monolith(hp: int) -> Image.Image:
    """THE DEBT: a jagged slab-titan. Big red eyes, a jagged glowing mouth and
    a burning $ in its chest. Cracks grow as hp drops; it always grins."""
    rng = random.Random(100 + hp)
    img = _img(96, 128)
    d = ImageDraw.Draw(img)
    slab = (26, 30, 35)
    edge = (50, 58, 66)
    top = [(12, 34), (20, 12), (29, 27), (38, 6), (47, 24), (57, 10), (66, 27), (76, 14), (83, 36)]
    d.polygon(top + [(83, 126), (12, 126)], fill=slab, outline=edge)
    for _ in range(30):  # moss of old unfinished things
        x, y = rng.randint(15, 80), rng.randint(38, 122)
        d.point((x, y), fill=(40, 47, 54))
        d.point((x + 1, y), fill=(33, 39, 45))
    # big glowing eyes with dark pupils
    eye = RED if hp > 1 else (110, 36, 33)
    d.rounded_rectangle([24, 42, 42, 58], 5, fill=eye, outline=(0, 0, 0))
    d.rounded_rectangle([54, 42, 72, 58], 5, fill=eye, outline=(0, 0, 0))
    d.rectangle([31, 46, 35, 54], fill=(10, 6, 6))
    d.rectangle([61, 46, 65, 54], fill=(10, 6, 6))
    # jagged glowing mouth
    mouth = [(30, 68), (36, 72), (42, 66), (48, 72), (54, 66), (60, 72), (66, 68)]
    d.line(mouth, fill=(200, 70, 50), width=3)
    # the burning debt: a $ core
    core = max(hp - 1, 0)
    glow = [(110, 44, 34), (180, 60, 38), (235, 90, 52), (255, 130, 80)][core]
    d.rectangle([30, 82, 65, 118], fill=(24, 12, 9))
    d.rectangle([30, 82, 65, 118], outline=glow)
    d.text((38, 84), "$", font=_font(36, bold=True), fill=glow)
    # cracks grow as hp drops
    for i in range(4 - hp):
        x, y = rng.randint(18, 74), rng.randint(36, 120)
        for _ in range(9):
            d.line([(x, y), (x + rng.randint(-6, 6), y + rng.randint(2, 8))], fill=(200, 210, 220), width=1)
            x += rng.randint(-6, 6)
            y += rng.randint(2, 8)
    if hp == 1:
        d.line([12, 40, 83, 74], fill=(200, 210, 220), width=2)
        d.line([83, 30, 12, 96], fill=(160, 170, 180), width=1)
    return img


def _imp_dead(color) -> Image.Image:
    """A squashed bug: flattened, legs up, x eyes. Your kill, while it lasts."""
    img = _img(48, 28)
    d = ImageDraw.Draw(img)
    dark = tuple(int(c * 0.5) for c in color)
    d.ellipse([6, 8, 42, 24], fill=color, outline=dark)  # flattened body
    d.ellipse([12, 10, 36, 20], fill=dark)
    for x0, x1 in ((2, 10), (38, 46)):  # legs sticking up
        d.line([(x0, 12), (x0 + 2, 2)], fill=dark, width=2)
        d.line([(x1, 12), (x1 - 2, 2)], fill=dark, width=2)
    f = _font(9, bold=True)
    d.text((17, 10), "x", font=f, fill=WHITE)
    d.text((26, 10), "x", font=f, fill=WHITE)
    return img


def _oldest_bug(hp: int) -> Image.Image:
    """THE OLDEST BUG: a hunched, crowned, grey-green elder imp. Three hits:
    crown straight -> crown crooked -> eyes out. It remembers 2009."""
    img = _img(96, 112)
    d = ImageDraw.Draw(img)
    skin = (108, 128, 104)
    dark = (62, 76, 60)
    gold = (247, 197, 66)
    # hunched body
    d.ellipse([10, 34, 86, 108], fill=(0, 0, 0))
    d.ellipse([12, 36, 84, 106], fill=skin, outline=dark)
    d.ellipse([24, 58, 72, 102], fill=dark)  # belly shadow
    # head
    d.ellipse([28, 14, 68, 50], fill=skin, outline=dark)
    # ears/horns
    d.polygon([(28, 22), (14, 8), (32, 12)], fill=dark)
    d.polygon([(68, 22), (82, 8), (64, 12)], fill=dark)
    # crown: straight at full hp, crooked when hurt
    tilt = 0 if hp == 3 else (6 if hp == 2 else 12)
    crown = [(36 + tilt, 6), (44, 14), (52, 4), (60, 14), (66 + tilt // 2, 8), (64, 20), (38, 20)]
    d.polygon(crown, fill=gold, outline=(150, 108, 24))
    # eyes: wide white with red pupils; X-ed out at hp 1
    if hp > 1:
        d.ellipse([36, 26, 48, 38], fill=WHITE, outline=(0, 0, 0))
        d.ellipse([52, 26, 64, 38], fill=WHITE, outline=(0, 0, 0))
        d.ellipse([40, 30, 44, 34], fill=RED)
        d.ellipse([56, 30, 60, 34], fill=RED)
    else:
        f = _font(12, bold=True)
        d.text((38, 26), "x", font=f, fill=(220, 90, 80))
        d.text((54, 26), "x", font=f, fill=(220, 90, 80))
    # grin
    d.line([(38, 44), (43, 41), (48, 44), (53, 41), (58, 44)], fill=(0, 0, 0), width=2)
    # arms
    d.ellipse([2, 46, 20, 66], fill=skin, outline=dark)
    d.ellipse([76, 46, 94, 66], fill=skin, outline=dark)
    if hp < 3:  # wounds
        d.line([(20, 60), (30, 80), (24, 96)], fill=(200, 210, 220), width=2)
    if hp == 1:
        d.line([(76, 56), (66, 84), (72, 100)], fill=(200, 210, 220), width=2)
        d.line([(48, 70), (44, 88)], fill=(150, 40, 36), width=2)
    return img


def make_sprites() -> dict[str, Image.Image]:
    colors = {"red": RED, "amber": AMBER, "purple": PURPLE, "green": GREEN, "cyan": CYAN}
    sprites = {f"bug_{n}": _imp(c) for n, c in colors.items()}
    sprites.update({f"bug_{n}_dead": _imp_dead(c) for n, c in colors.items()})
    sprites["key"] = _key_badge()
    sprites["ancient3"] = _oldest_bug(3)
    sprites["ancient2"] = _oldest_bug(2)
    sprites["ancient1"] = _oldest_bug(1)
    sprites["boss"] = _monolith(4)
    sprites["boss3"] = _monolith(3)
    sprites["boss2"] = _monolith(2)
    sprites["boss1"] = _monolith(1)
    return sprites


# ---------------------------------------------------------------- banners

def _scanlines(img: Image.Image) -> Image.Image:
    px = img.load()
    for y in range(3, img.height, 3):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            px[x, y] = (int(r * 0.72), int(g * 0.72), int(b * 0.72), a)
    return img


def make_title(w: int = 960, h: int = 600) -> Image.Image:
    img = _img(w, h, BG + (255,))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, w - 1, h - 1], outline=(48, 54, 61), width=2)
    f_big = _font(92, bold=True)
    f_sub = _font(26)
    f_menu = _font(30, bold=True)
    d.text((w // 2, 150), "DETACHED", font=f_big, fill=GREEN, anchor="mm")
    d.text((w // 2, 260), "HEAD", font=f_big, fill=GREEN, anchor="mm")
    d.text((w // 2, 360), "you fell asleep at your desk", font=f_sub, fill=GRAY, anchor="mm")
    d.text((w // 2, 400), "and woke up inside the repository", font=f_sub, fill=GRAY, anchor="mm")
    d.text((w // 2, 500), "press START", font=f_menu, fill=WHITE, anchor="mm")
    return _scanlines(img)


def make_win(w: int = 960, h: int = 600) -> Image.Image:
    img = _img(w, h, (6, 20, 10, 255))
    d = ImageDraw.Draw(img)
    f_big = _font(96, bold=True)
    f_sub = _font(26)
    d.text((w // 2, 170), "YOU ESCAPED", font=f_big, fill=GREEN, anchor="mm")
    d.text((w // 2, 280), "THE DEBT is deleted", font=f_sub, fill=WHITE, anchor="mm")
    for i, line in enumerate(("build    \u2713 passed", "tests   \u2713 1337 passed", "deploy  \u2713 shipped")):
        d.text((w // 2, 370 + i * 36), line, font=_font(24), fill=GRAY, anchor="mm")
    d.text((w // 2, 520), "you may go home now.", font=f_sub, fill=GREEN, anchor="mm")
    d.text((w // 2, 560), "cleanup crew: git blame", font=_font(18), fill=(90, 98, 106), anchor="mm")
    return _scanlines(img)


def make_minimap_banner(lvl, w: int = 960, h: int = 600) -> Image.Image:
    """Standalone map overview for the README."""
    img = _img(w, h, BG + (255,))
    d = ImageDraw.Draw(img)
    cell = 20
    ox = (w - lvl.width * cell) // 2
    oy = (h - lvl.height * cell) // 2
    palette = {"arena": (70, 20, 20), "keyroom": (60, 50, 12), "gate": (70, 60, 20)}
    for y in range(lvl.height):
        for x in range(lvl.width):
            c = lvl.char(x, y)
            if lvl.is_floor(x, y):
                z = lvl.zone(x, y)
                color = palette.get(z, (27, 33, 41))
                if c == "G":
                    color = AMBER
                d.rectangle([ox + x * cell, oy + y * cell, ox + x * cell + cell - 2, oy + y * cell + cell - 2], fill=color)
            else:
                d.rectangle([ox + x * cell, oy + y * cell, ox + x * cell + cell - 2, oy + y * cell + cell - 2], fill=(13, 17, 23), outline=(48, 54, 61))
    d.ellipse([ox + lvl.spawn[0] * cell + 4, oy + lvl.spawn[1] * cell + 4, ox + lvl.spawn[0] * cell + cell - 6, oy + lvl.spawn[1] * cell + cell - 6], fill=GREEN)
    d.text((w // 2, oy - 40), "repo-01 \u00b7 the repository", font=_font(30, bold=True), fill=GREEN, anchor="mm")
    d.text((w // 2, h - 40), "find the key \u00b7 open the gate \u00b7 slay THE DEBT", font=_font(20), fill=GRAY, anchor="mm")
    return _scanlines(img)
